apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-principal
  namespace: metallb-system
spec:
  addresses:
  - 172.24.14.170-172.24.14.190   # ← AJUSTA ESTE RANGO según tu red
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool-principal
